import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Product from './models/Product.js';

dotenv.config();

const products = [
  // Shirts
  {
    name: 'Pattern Shirt White',
    category: 'shirts',
    price: 650,
    originalPrice: 1500,
    image: '/Shirts/shirt-pattern-3.jpg',
    rating: 4.5,
    reviews: 128,
    badge: 'Bestseller',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    name: 'Stylish Blue Shirt',
    category: 'shirts',
    price: 550,
    originalPrice: 1400,
    image: '/Shirts/shirt-blue.jpg',
    rating: 4.3,
    reviews: 96,
    badge: '',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name: 'Stylish Gray Shirt',
    category: 'shirts',
    price: 450,
    originalPrice: 1200,
    image: '/Shirts/shirt-gray.jpg',
    rating: 4.7,
    reviews: 214,
    badge: 'Premium',
    sizes: ['M', 'L', 'XL'],
  },
  {
    name: 'Stylish Green Shirt',
    category: 'shirts',
    price: 500,
    originalPrice: 1300,
    image: '/Shirts/shirt-green.jpg',
    rating: 4.1,
    reviews: 67,
    badge: 'New',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    name: 'Premium Printed Shirt',
    category: 'shirts',
    price: 650,
    originalPrice: 1800,
    image: '/Shirts/shirt-pattern-1.jpg',
    rating: 4.4,
    reviews: 153,
    badge: '',
    sizes: ['S', 'M', 'L'],
  },
  {
    name: 'Modern Printed Shirt',
    category: 'shirts',
    price: 450,
    originalPrice: 1500,
    image: '/Shirts/shirt-pattern-2.jpg',
    rating: 4.2,
    reviews: 89,
    badge: 'Sale',
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    name: 'Printed Shirt',
    category: 'shirts',
    price: 550,
    originalPrice: 1400,
    image: '/Shirts/shirt-pattern-gray.jpg',
    rating: 4.2,
    reviews: 89,
    badge: 'Sale',
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    name: 'Printed Shirt Gray',
    category: 'shirts',
    price: 600,
    originalPrice: 1500,
    image: '/Shirts/shirt-pattern.jpg',
    rating: 4.2,
    reviews: 89,
    badge: 'Sale',
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    name: 'Modern Printed Shirt',
    category: 'shirts',
    price: 450,
    originalPrice: 1300,
    image: '/Shirts/shirt-pink.jpg',
    rating: 4.2,
    reviews: 89,
    badge: 'Sale',
    sizes: ['M', 'L', 'XL', 'XXL'],
  },
  {
    name: 'Checkers Pattern Shirt',
    category: 'shirts',
    price: 400,
    originalPrice: 1800,
    image: '/Shirts/shirt-hero.jpg',
    rating: 4.2,
    reviews: 89,
    badge: 'Sale',
    sizes: ['M', 'L', 'XL', 'XXL'],
  },

  // T-Shirts
  {
    name: 'Fancy Red T-shirt',
    category: 'tshirts',
    price: 350,
    originalPrice: 999,
    image: '/T-Shirts/fancy-tshirt-red.jpg',
    rating: 4.6,
    reviews: 342,
    badge: 'Bestseller',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name: 'Black Addidas Tshirt',
    category: 'tshirts',
    price: 300,
    originalPrice: 900,
    image: '/T-Shirts/tshirt-black-addidas.jpg',
    rating: 4.4,
    reviews: 276,
    badge: '',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    name: 'Blue Addidas Tshirt',
    category: 'tshirts',
    price: 250,
    originalPrice: 800,
    image: '/T-Shirts/tshirt-blue-addidas.jpg',
    rating: 4.3,
    reviews: 198,
    badge: '',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    name: 'Minimal Black Tshirt',
    category: 'tshirts',
    price: 200,
    originalPrice: 750,
    image: '/T-Shirts/tshirt-black.jpg',
    rating: 4.5,
    reviews: 156,
    badge: 'Trending',
    sizes: ['M', 'L', 'XL'],
  },
  {
    name: 'Minimal Blue Tshirt',
    category: 'tshirts',
    price: 300,
    originalPrice: 800,
    image: '/T-Shirts/tshirt-blue.jpg',
    rating: 4.7,
    reviews: 87,
    badge: 'New',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    name: 'Minimal Brown Tshirt',
    category: 'tshirts',
    price: 200,
    originalPrice: 650,
    image: '/T-Shirts/tshirt-brown.jpg',
    rating: 4.2,
    reviews: 134,
    badge: 'Sale',
    sizes: ['S', 'M', 'L'],
  },
  {
    name: 'Minimal Gray Tshirt',
    category: 'tshirts',
    price: 200,
    originalPrice: 700,
    image: '/T-Shirts/tshirt-gray.jpg',
    rating: 4.2,
    reviews: 134,
    badge: 'Sale',
    sizes: ['S', 'M', 'L'],
  },
  {
    name: 'Printed Nike Tshirt',
    category: 'tshirts',
    price: 250,
    originalPrice: 800,
    image: '/T-Shirts/tshirt-printend-nike.jpg',
    rating: 4.2,
    reviews: 134,
    badge: 'Sale',
    sizes: ['S', 'M', 'L'],
  },
  {
    name: 'Minimal White Tshirt',
    category: 'tshirts',
    price: 200,
    originalPrice: 700,
    image: '/T-Shirts/tshirt-white.jpg',
    rating: 4.2,
    reviews: 134,
    badge: 'Sale',
    sizes: ['S', 'M', 'L'],
  },
  {
    name: 'Multi-Color Tshirts',
    category: 'tshirts',
    price: 150,
    originalPrice: 800,
    image: '/T-Shirts/tshirts-multicolor.jpg',
    rating: 4.2,
    reviews: 134,
    badge: 'Sale',
    sizes: ['S', 'M', 'L'],
  },

  // Jeans
  {
    name: 'Black Jeans Casual',
    category: 'jeans',
    price: 850,
    originalPrice: 1500,
    image: '/Jeans/jeans-black-casual.jpg',
    rating: 4.8,
    reviews: 421,
    badge: 'Bestseller',
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    name: 'OverSized Jeans',
    category: 'jeans',
    price: 900,
    originalPrice: 1600,
    image: '/Jeans/jeans-big-pocket.jpg',
    rating: 4.6,
    reviews: 298,
    badge: 'Premium',
    sizes: ['28', '30', '32', '34'],
  },
  {
    name: 'Slim Fit Black Jeans',
    category: 'jeans',
    price: 800,
    originalPrice: 1300,
    image: '/Jeans/jeans-black.jpg',
    rating: 4.4,
    reviews: 187,
    badge: '',
    sizes: ['30', '32', '34', '36'],
  },
  {
    name: 'Blue Jeans Casual',
    category: 'jeans',
    price: 750,
    originalPrice: 1400,
    image: '/Jeans/jeans-blue-casual.jpg',
    rating: 4.5,
    reviews: 156,
    badge: 'New',
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    name: 'Fancy Jeans Torn',
    category: 'jeans',
    price: 800,
    originalPrice: 1400,
    image: '/Jeans/jeans-fancy.jpg',
    rating: 4.3,
    reviews: 112,
    badge: '',
    sizes: ['30', '32', '34'],
  },
  {
    name: 'Blue Jeans',
    category: 'jeans',
    price: 800,
    originalPrice: 1200,
    image: '/Jeans/jeans-blue.jpg',
    rating: 4.6,
    reviews: 203,
    badge: 'Sale',
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    name: 'Jeans Torn',
    category: 'jeans',
    price: 950,
    originalPrice: 1200,
    image: '/Jeans/jeans-fancy-2.jpg',
    rating: 4.6,
    reviews: 203,
    badge: 'Sale',
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    name: 'Gray Jeans Casual',
    category: 'jeans',
    price: 750,
    originalPrice: 1200,
    image: '/Jeans/jeans-gray-casual.jpg',
    rating: 4.6,
    reviews: 203,
    badge: 'Sale',
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    name: 'Gray Jeans',
    category: 'jeans',
    price: 850,
    originalPrice: 1200,
    image: '/Jeans/jeans-gray.jpg',
    rating: 4.6,
    reviews: 203,
    badge: 'Sale',
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    name: 'Modern Blue Jeans ',
    category: 'jeans',
    price: 1000,
    originalPrice: 1600,
    image: '/Jeans/jeans-hero.jpg',
    rating: 4.6,
    reviews: 203,
    badge: 'Sale',
    sizes: ['28', '30', '32', '34', '36'],
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB Connected for Seeding');
    
    await Product.deleteMany({});
    console.log('Existing products removed');
    
    await Product.insertMany(products);
    console.log('Products seeded successfully');
    
    process.exit();
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDB();
